---
name: Unit Tests

on:
  pull_request:

permissions: {}

jobs:
  unit-testing:
    name: Go Unit Tests
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683

      - name: Create artifacts directory
        run: mkdir artifacts

      - name: Run Go unit tests
        run: |
          set -o pipefail
          make unit 2>&1 | tee artifacts/unittest.log

      - name: Collect artifacts
        run: |
          for f in $(find ./pkg -name "*.xml"); do
            mkdir -p artifacts/$(dirname $f)
            cp $f -rfp artifacts/$f
          done

      - name: Upload artifacts
        uses: actions/upload-artifact@65c4c4a1ddee5b72f698fdd19549f0f0fb45cf08
        with:
          name: Unit test artifacts
          path: artifacts

      - name: Run SonarScan, upload Go test results and coverage
        uses: SonarSource/sonarqube-scan-action@0303d6b62e310685c0e34d0b9cde218036885c4d
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
